fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "2.6.0"
    apt: 
      repo: "https://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "1.4.1"
  symlinks:
    cassandra: "#{source_dir}"
